#!/bin/bash

# multilink, serial, wirelessmodem interfaces pass cli configured
# interface name as the 1st word in ipparam while pppoe and pppoa
# interfaces pass just the configured interface name using ipparam
device=`echo "$6"|awk '{ print $1 }'`

# only do this script for ml, wan, pppoe, pppoa, wlm interfaces
# any new interfaces using ppp in CLI will have to be passed
# using ipparam and have to add themselves here
case "$device"X in
 ml* | wan* | pppoa* | pppoe* | wlm* );;
 * )
    logger -p debug -t "vyatta-usepeerdns" \
    Invalid interface $device to update resolv.conf on link down
    exit 0;;
esac
rm -f /etc/ppp/resolv-$device.conf
vyos-hostsd-client --delete-name-servers --tag $device

# restart the DNS server if dns-forwarding is configured
if cli-shell-api existsActive service dns forwarding; then
  systemctl restart pdns-recursor
fi

# restart ntp if ntp is configured
if [ -f /etc/ntp.conf ] && grep -q "^server" /etc/ntp.conf; then
   /usr/sbin/invoke-rc.d ntp restart >&/dev/null
fi

exit 0

