#!/bin/bash

# this variable is only set if the usepeerdns pppd option is being used
[ "$USEPEERDNS" ] || exit 0

# multilink, serial, wirelessmodem interfaces pass cli configured
# interface name as the 1st word in ipparam while pppoe and pppoa
# interfaces pass just the configured interface name using ipparam
device=`echo "$6"|awk '{ print $1 }'`

# only do this script for ml, wan, pppoe, pppoa, wlm interfaces
# any new interfaces using ppp in CLI will have to be passed
# using ipparam and have to add themselves here
case "$device"X in
 ml* | wan* | pppoa* | pppoe* | wlm* );;
 * )
    logger -p debug -t "vyatta-usepeerdns" \
    Invalid interface $device to update resolv.conf on link up
    exit 0;;
esac

# create the file if it does not exist
if [ ! -e /etc/resolv.conf ]; then
  : > /etc/resolv.conf
fi

# store nameservers received for this ppp device in its own resolv-$device.conf file
# TODO : need to lock /etc/ppp/resolv.conf while copying it
cp -p /etc/ppp/resolv.conf /etc/ppp/resolv-$device.conf

# Add name servers to the system configuration
nameserver_array=($( grep '^nameserver' /etc/ppp/resolv-$device.conf | awk '{print $2}' ))
ns_array_len=${#nameserver_array[*]}
i=0
vc_opts=""
while [ $i -lt $ns_array_len ]; do
 vc_opts="$vc_opts --name-server ${nameserver_array[$i]}"
 let i++
done
vyos-hostsd-client --add-name-servers --tag $device $vc_opts

# restart the DNS server if dns-forwarding is configured
if cli-shell-api existsActive service dns forwarding; then
   systemctl restart pdns-recursor >&/dev/null
fi

exit 0

